### PR TITLE
Display questions added in for HVAC2

### PR DESCRIPTION
**Pull request by k8mckay**

### CODE REVIEW

**Review by liamdmccann — CHANGES_REQUESTED** [review]
hiya, can't push this in yet. two key things:

a. why are we replacing is_registered_in_GEMS with HVAC2_appliance_is_registered_in_GEMS? the former variable is intended as a generic variable used to encompass all of the instances where we require GEMS registration in the rule(s). is there a specific scenario or reason that is different about this particular GEMS registration that requires a different form of variable?

b. replacing is_not_residential with is_commercial is not accurate. the requirement in the rule states:

2.	The New End-User Equipment or replacement End-User Equipment must not be installed in a Residential Building unless the activity is the replacement of an existing air conditioner in a centralised system or in the common areas of a Class 2 building.

note, there are several building types in the BCA building list (found here: https://www.abcb.gov.au/sites/default/files/resources/2022/UTNCC-Building-classifications.PDF) which are not commercial. therefore, the existing requirement was accurate and this revision is not accurate - please update.

**Comment by k8mckay** [comment]
Hello!
(Notes below in pink)


 <http://www.katemckay.ca/>				
Kate		
email:	***@***.*** ***@***.***>		
website:	www.katemckay.ca <http://www.katemckay.ca/>		
I work and live on the lands of the Wiradjuri people and acknowledge that sovereignty was never ceded.
I pay my respects to elders past, present and emerging across Australia. 
This always was, and always will be, Aboriginal land.			
 <https://www.facebook.com/katemckaydesign/>		 <https://www.linkedin.com/in/kate-mckay-8334991b/>

**Review by liamdmccann — CHANGES_REQUESTED** [review]
sorry to be a bit neurotic, but:
- could you please use the variable "ESS_is_not_residential_building" (happy to re-name) instead? 

we should only have one variable that determines whether a building is residential or not - and by residential, I mean the definition in section 10.1 of the ESS Rule. This is also in section 10.1 of the PDRS Rule. 

This already has the logic for determining whether it's residential based on BCA building type built in. You can either a. ask for the BCA building type (and give them an enum dropdown list to choose from, linking in with this variable) or b. simply ask if they're residential and link to the overarching variable.

But, we should not have two variables asking if a building type is residential in the code - we have a set definition for what residential is in the whole rule and so should use one definition through the whole rule - so, politely - please use the existing variable. 

(You also need to amend the variable name in the tests to make sure it's testing whether residential is false!)

**Review by liamdmccann — APPROVED** [review]
cool! we still need to fix the residential variable but I'll jump in as part of my reforming previous fellowship work

**Pull request merged**
